[2024-05-28T10:03:16.951+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:03:16.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:03:16.965+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:03:16.964+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:03:16.983+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:03:16.971+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:03:16.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:03:17.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.145 seconds
[2024-05-28T10:03:47.238+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:03:47.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:03:47.242+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:03:47.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:03:47.246+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:03:47.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:03:47.247+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:03:47.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.081 seconds
[2024-05-28T10:04:17.477+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:04:17.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:04:17.493+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:04:17.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:04:17.504+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:04:17.498+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:04:17.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:04:17.550+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.080 seconds
[2024-05-28T10:04:47.780+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:04:47.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:04:47.791+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:04:47.787+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:04:47.799+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:04:47.797+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:04:47.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:04:47.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.102 seconds
[2024-05-28T10:05:18.326+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:05:18.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:05:18.331+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:05:18.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:05:18.336+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:05:18.334+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:05:18.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:05:18.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.066 seconds
[2024-05-28T10:05:48.645+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:05:48.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:05:48.666+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:05:48.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:05:48.681+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:05:48.676+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:05:48.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:05:48.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.126 seconds
[2024-05-28T10:06:19.090+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:06:19.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:06:19.096+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:06:19.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:06:19.104+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:06:19.100+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:06:19.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:06:19.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.079 seconds
[2024-05-28T10:06:49.364+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:06:49.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:06:49.369+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:06:49.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:06:49.373+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:06:49.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:06:49.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:06:49.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-28T10:07:20.325+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:07:20.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:07:20.331+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:07:20.330+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:07:20.336+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:07:20.334+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:07:20.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:07:20.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.108 seconds
[2024-05-28T10:07:50.612+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:07:50.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:07:50.619+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:07:50.619+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:07:50.624+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:07:50.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:07:50.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:07:50.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.055 seconds
[2024-05-28T10:08:21.058+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:08:21.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:08:21.063+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:08:21.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:08:21.072+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:08:21.068+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:08:21.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:08:21.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.101 seconds
[2024-05-28T10:08:51.353+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:08:51.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:08:51.358+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:08:51.358+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:08:51.364+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:08:51.362+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:08:51.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:08:51.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-28T10:09:21.699+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:09:21.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:09:21.704+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:09:21.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:09:21.708+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:09:21.707+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:09:21.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:09:21.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.056 seconds
[2024-05-28T10:09:51.844+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:09:51.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:09:51.852+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:09:51.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:09:51.866+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:09:51.864+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:09:51.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:09:51.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.086 seconds
[2024-05-28T10:10:22.012+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:10:22.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:10:22.015+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:10:22.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:10:22.019+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:10:22.017+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:10:22.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:10:22.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.047 seconds
[2024-05-28T10:10:52.466+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:10:52.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:10:52.474+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:10:52.473+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:10:52.485+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:10:52.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:10:52.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:10:52.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.079 seconds
[2024-05-28T10:11:22.708+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:11:22.711+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:11:22.713+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:11:22.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:11:22.717+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:11:22.716+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:11:22.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:11:22.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-28T10:11:53.582+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:11:53.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:11:53.586+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:11:53.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:11:53.590+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:11:53.589+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:11:53.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:11:53.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.054 seconds
[2024-05-28T10:12:23.781+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:12:23.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:12:23.785+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:12:23.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:12:23.790+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:12:23.789+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:12:23.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:12:23.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.078 seconds
[2024-05-28T10:12:54.044+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:12:54.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:12:54.054+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:12:54.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:12:54.063+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:12:54.061+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:12:54.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:12:54.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.070 seconds
[2024-05-28T10:13:24.307+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:13:24.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:13:24.313+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:13:24.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:13:24.318+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:13:24.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:13:24.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:13:24.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.069 seconds
[2024-05-28T10:13:54.524+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:13:54.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:13:54.531+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:13:54.530+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:13:54.539+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:13:54.537+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:13:54.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:13:54.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.099 seconds
[2024-05-28T10:14:24.658+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:14:24.662+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:14:24.670+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:14:24.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:14:24.674+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:14:24.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:14:24.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:14:24.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.078 seconds
[2024-05-28T10:14:54.905+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:14:54.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:14:54.917+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:14:54.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:14:54.924+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:14:54.922+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:14:54.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:14:54.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.081 seconds
[2024-05-28T10:15:25.229+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:15:25.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:15:25.241+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:15:25.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:15:25.259+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:15:25.250+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:15:25.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:15:25.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.108 seconds
[2024-05-28T10:15:55.472+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:15:55.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:15:55.475+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:15:55.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:15:55.479+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:15:55.477+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:15:55.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:15:55.507+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.044 seconds
[2024-05-28T10:16:25.767+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:16:25.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:16:25.775+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:16:25.774+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:16:25.780+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:16:25.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:16:25.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:16:25.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-28T10:16:56.118+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:16:56.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:16:56.126+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:16:56.125+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:16:56.133+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:16:56.131+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:16:56.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:16:56.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.095 seconds
[2024-05-28T10:17:26.367+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:17:26.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:17:26.371+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:17:26.370+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:17:26.375+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:17:26.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:17:26.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:17:26.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.048 seconds
[2024-05-28T10:17:56.585+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:17:56.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:17:56.590+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:17:56.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:17:56.593+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:17:56.592+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:17:56.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:17:56.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.064 seconds
[2024-05-28T10:18:26.715+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:18:26.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:18:26.729+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:18:26.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:18:26.739+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:18:26.737+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:18:26.741+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:18:26.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.097 seconds
[2024-05-28T10:18:56.990+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:18:56.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:18:56.994+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:18:56.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:18:56.999+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:18:56.997+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:18:57.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:18:57.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.079 seconds
[2024-05-28T10:19:27.290+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:19:27.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:19:27.300+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:19:27.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:19:27.307+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:19:27.305+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:19:27.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:19:27.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.094 seconds
[2024-05-28T10:19:57.551+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:19:57.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:19:57.554+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:19:57.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:19:57.573+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:19:57.572+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:19:57.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:19:57.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.072 seconds
[2024-05-28T10:20:27.742+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:20:27.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:20:27.756+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:20:27.755+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:20:27.773+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:20:27.768+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:20:27.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:20:27.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.092 seconds
[2024-05-28T10:20:57.858+0000] {processor.py:161} INFO - Started process (PID=416) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:20:57.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:20:57.866+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:20:57.866+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:20:57.878+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:20:57.874+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:20:57.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:20:57.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.098 seconds
[2024-05-28T10:21:28.057+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:21:28.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:21:28.063+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:21:28.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:21:28.070+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:21:28.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:21:28.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:21:28.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.058 seconds
[2024-05-28T10:21:58.175+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:21:58.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:21:58.181+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:21:58.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:21:58.190+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:21:58.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:21:58.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:21:58.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.069 seconds
[2024-05-28T10:22:28.401+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:22:28.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:22:28.408+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:22:28.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:22:28.423+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:22:28.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:22:28.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:22:28.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.070 seconds
[2024-05-28T10:22:58.632+0000] {processor.py:161} INFO - Started process (PID=460) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:22:58.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:22:58.635+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:22:58.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:22:58.639+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:22:58.638+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:22:58.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:22:58.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.078 seconds
[2024-05-28T10:23:28.916+0000] {processor.py:161} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:23:28.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:23:28.920+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:23:28.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:23:28.932+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:23:28.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:23:28.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:23:28.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.072 seconds
[2024-05-28T10:23:59.923+0000] {processor.py:161} INFO - Started process (PID=483) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:23:59.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:23:59.936+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:23:59.935+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:23:59.944+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:23:59.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:23:59.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:23:59.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.082 seconds
[2024-05-28T10:24:30.197+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:24:30.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:24:30.206+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:24:30.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:24:30.215+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:24:30.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:24:30.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:24:30.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.083 seconds
[2024-05-28T10:25:01.149+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:25:01.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:25:01.154+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:25:01.153+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:25:01.162+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:25:01.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:25:01.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:25:01.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.066 seconds
[2024-05-28T10:25:32.120+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:25:32.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:25:32.124+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:25:32.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:25:32.127+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:25:32.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:25:32.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:25:32.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.045 seconds
[2024-05-28T10:26:02.380+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:26:02.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:26:02.393+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:26:02.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:26:02.401+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:26:02.399+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:26:02.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:26:02.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.083 seconds
[2024-05-28T10:26:32.664+0000] {processor.py:161} INFO - Started process (PID=538) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:26:32.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:26:32.674+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:26:32.674+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:26:32.691+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:26:32.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:26:32.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:26:32.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.078 seconds
[2024-05-28T10:27:02.897+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:27:02.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:27:02.902+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:27:02.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:27:02.907+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:27:02.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:27:02.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:27:02.982+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.095 seconds
[2024-05-28T10:27:33.248+0000] {processor.py:161} INFO - Started process (PID=560) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:27:33.250+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:27:33.254+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:27:33.254+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:27:33.259+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:27:33.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:27:33.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:27:33.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.088 seconds
[2024-05-28T10:28:03.441+0000] {processor.py:161} INFO - Started process (PID=570) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:28:03.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:28:03.447+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:28:03.446+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:28:03.451+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:28:03.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:28:03.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:28:03.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.062 seconds
[2024-05-28T10:28:33.690+0000] {processor.py:161} INFO - Started process (PID=581) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:28:33.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:28:33.693+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:28:33.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:28:33.699+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:28:33.697+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:28:33.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:28:33.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-28T10:29:04.621+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:29:04.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:29:04.624+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:29:04.624+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:29:04.631+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:29:04.629+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:29:04.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:29:04.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.047 seconds
[2024-05-28T10:29:34.881+0000] {processor.py:161} INFO - Started process (PID=603) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:29:34.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:29:34.889+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:29:34.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:29:34.898+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:29:34.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:29:34.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:29:34.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.073 seconds
[2024-05-28T10:30:05.003+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:30:05.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-28T10:30:05.009+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:30:05.009+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:30:05.023+0000] {logging_mixin.py:188} INFO - [2024-05-28T10:30:05.015+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-28T10:30:05.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-28T10:30:05.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.106 seconds
