[2024-05-30T07:42:52.324+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:42:52.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:42:52.327+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:42:52.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:42:52.332+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:42:52.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:42:52.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:42:52.365+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.049 seconds
[2024-05-30T07:43:22.707+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:43:22.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:43:22.712+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:43:22.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:43:22.718+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:43:22.716+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:43:22.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:43:22.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.055 seconds
[2024-05-30T07:43:52.935+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:43:52.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:43:52.938+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:43:52.938+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:43:52.942+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:43:52.941+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:43:52.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:43:52.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.045 seconds
[2024-05-30T07:44:23.150+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:44:23.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:44:23.154+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:44:23.153+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:44:23.158+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:44:23.156+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:44:23.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:44:23.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.050 seconds
[2024-05-30T07:44:53.414+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:44:53.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:44:53.419+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:44:53.419+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:44:53.426+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:44:53.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:44:53.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:44:53.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.075 seconds
[2024-05-30T07:45:23.646+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:45:23.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:45:23.650+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:45:23.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:45:23.654+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:45:23.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:45:23.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:45:23.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.051 seconds
[2024-05-30T07:45:53.852+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:45:53.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:45:53.855+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:45:53.854+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:45:53.858+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:45:53.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:45:53.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:45:53.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.047 seconds
[2024-05-30T07:46:24.049+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:46:24.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:46:24.053+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:46:24.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:46:24.057+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:46:24.056+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:46:24.057+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:46:24.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-30T07:46:54.278+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:46:54.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:46:54.283+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:46:54.282+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:46:54.290+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:46:54.287+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:46:54.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:46:54.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.058 seconds
[2024-05-30T07:47:25.181+0000] {processor.py:161} INFO - Started process (PID=132) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:47:25.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:47:25.184+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:47:25.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:47:25.187+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:47:25.186+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:47:25.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:47:25.230+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.057 seconds
[2024-05-30T07:47:55.387+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:47:55.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:47:55.397+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:47:55.397+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:47:55.403+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:47:55.402+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:47:55.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:47:55.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.067 seconds
[2024-05-30T07:48:26.247+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:48:26.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:48:26.251+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:48:26.251+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:48:26.255+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:48:26.254+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:48:26.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:48:26.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.042 seconds
[2024-05-30T07:48:56.446+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:48:56.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:48:56.450+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:48:56.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:48:56.453+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:48:56.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:48:56.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:48:56.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.050 seconds
[2024-05-30T07:49:26.665+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:49:26.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:49:26.671+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:49:26.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:49:26.676+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:49:26.675+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:49:26.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:49:26.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-30T07:49:56.952+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:49:56.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:49:56.956+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:49:56.955+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:49:56.960+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:49:56.959+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:49:56.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:49:56.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.040 seconds
[2024-05-30T07:50:27.945+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:50:27.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:50:27.949+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:50:27.948+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:50:27.954+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:50:27.952+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:50:27.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:50:27.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.043 seconds
[2024-05-30T07:50:58.802+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:50:58.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:50:58.808+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:50:58.807+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:50:58.814+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:50:58.812+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:50:58.815+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:50:58.842+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.049 seconds
[2024-05-30T07:51:29.022+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:51:29.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:51:29.027+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:51:29.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:51:29.031+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:51:29.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:51:29.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:51:29.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.043 seconds
[2024-05-30T07:51:59.214+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:51:59.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:51:59.218+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:51:59.218+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:51:59.222+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:51:59.221+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:51:59.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:51:59.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.044 seconds
[2024-05-30T07:52:29.429+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:52:29.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:52:29.434+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:52:29.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:52:29.439+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:52:29.437+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:52:29.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:52:29.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.060 seconds
[2024-05-30T07:52:59.667+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:52:59.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:52:59.670+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:52:59.670+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:52:59.674+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:52:59.673+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:52:59.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:52:59.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.048 seconds
[2024-05-30T07:53:29.862+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:53:29.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:53:29.865+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:53:29.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:53:29.870+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:53:29.868+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:53:29.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:53:29.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.044 seconds
[2024-05-30T07:54:00.083+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:54:00.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:54:00.093+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:54:00.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:54:00.098+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:54:00.097+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:54:00.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:54:00.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.074 seconds
[2024-05-30T07:54:30.318+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:54:30.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:54:30.324+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:54:30.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:54:30.330+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:54:30.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:54:30.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:54:30.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.053 seconds
[2024-05-30T07:55:00.528+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:55:00.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:55:00.531+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:55:00.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:55:00.536+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:55:00.533+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:55:00.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:55:00.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.056 seconds
[2024-05-30T07:55:30.756+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:55:30.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:55:30.761+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:55:30.760+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:55:30.764+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:55:30.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:55:30.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:55:30.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.044 seconds
[2024-05-30T07:56:00.976+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:56:00.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:56:00.979+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:56:00.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:56:00.982+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:56:00.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:56:00.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:56:01.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.051 seconds
[2024-05-30T07:56:31.186+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:56:31.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:56:31.191+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:56:31.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:56:31.195+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:56:31.194+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:56:31.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:56:31.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-30T07:57:01.421+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:57:01.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:57:01.429+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:57:01.428+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:57:01.443+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:57:01.438+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:57:01.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:57:01.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.075 seconds
[2024-05-30T07:57:31.663+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:57:31.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:57:31.666+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:57:31.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:57:31.671+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:57:31.670+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:57:31.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:57:31.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.048 seconds
[2024-05-30T07:58:01.896+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:58:01.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:58:01.902+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:58:01.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:58:01.907+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:58:01.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:58:01.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:58:01.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.053 seconds
[2024-05-30T07:58:32.151+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:58:32.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:58:32.154+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:58:32.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:58:32.161+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:58:32.160+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:58:32.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:58:32.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.052 seconds
[2024-05-30T07:59:02.367+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:59:02.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:59:02.373+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:59:02.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:59:02.376+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:59:02.375+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:59:02.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:59:02.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.085 seconds
[2024-05-30T07:59:32.636+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:59:32.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T07:59:32.644+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:59:32.643+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:59:32.649+0000] {logging_mixin.py:188} INFO - [2024-05-30T07:59:32.647+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T07:59:32.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T07:59:32.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.091 seconds
[2024-05-30T08:00:03.035+0000] {processor.py:161} INFO - Started process (PID=402) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:00:03.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:00:03.042+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:00:03.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:00:03.049+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:00:03.047+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:00:03.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:00:03.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.083 seconds
[2024-05-30T08:00:33.290+0000] {processor.py:161} INFO - Started process (PID=412) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:00:33.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:00:33.292+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:00:33.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:00:33.296+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:00:33.295+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:00:33.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:00:33.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.072 seconds
[2024-05-30T08:01:03.497+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:01:03.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:01:03.514+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:01:03.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:01:03.521+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:01:03.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:01:03.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:01:03.562+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.092 seconds
[2024-05-30T08:01:33.769+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:01:33.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:01:33.778+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:01:33.777+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:01:33.787+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:01:33.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:01:33.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:01:33.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.080 seconds
[2024-05-30T08:02:04.040+0000] {processor.py:161} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:02:04.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:02:04.046+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:02:04.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:02:04.051+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:02:04.049+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:02:04.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:02:04.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.046 seconds
[2024-05-30T08:02:35.002+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:02:35.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:02:35.006+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:02:35.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:02:35.011+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:02:35.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:02:35.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:02:35.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.051 seconds
[2024-05-30T08:03:05.228+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:03:05.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:03:05.233+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:03:05.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:03:05.237+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:03:05.235+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:03:05.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:03:05.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.047 seconds
[2024-05-30T08:03:35.454+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:03:35.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:03:35.456+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:03:35.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:03:35.462+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:03:35.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:03:35.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:03:35.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.064 seconds
[2024-05-30T08:04:05.712+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:04:05.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:04:05.716+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:04:05.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:04:05.722+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:04:05.721+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:04:05.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:04:05.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.104 seconds
[2024-05-30T08:04:36.023+0000] {processor.py:161} INFO - Started process (PID=495) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:04:36.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:04:36.028+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:04:36.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:04:36.042+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:04:36.032+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:04:36.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:04:36.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.109 seconds
[2024-05-30T08:05:06.340+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:05:06.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:05:06.345+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:05:06.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:05:06.368+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:05:06.362+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:05:06.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:05:06.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.106 seconds
[2024-05-30T08:05:36.667+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:05:36.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:05:36.673+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:05:36.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:05:36.682+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:05:36.677+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:05:36.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:05:36.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.085 seconds
[2024-05-30T08:06:07.006+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:06:07.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:06:07.017+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:06:07.014+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:06:07.024+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:06:07.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:06:07.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:06:07.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.099 seconds
[2024-05-30T08:06:37.241+0000] {processor.py:161} INFO - Started process (PID=639) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:06:37.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:06:37.243+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:06:37.243+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:06:37.248+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:06:37.247+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:06:37.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:06:37.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.078 seconds
[2024-05-30T08:07:07.501+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:07:07.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:07:07.505+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:07:07.505+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:07:07.510+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:07:07.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:07:07.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:07:07.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.059 seconds
[2024-05-30T08:07:37.756+0000] {processor.py:161} INFO - Started process (PID=733) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:07:37.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:07:37.759+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:07:37.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:07:37.762+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:07:37.761+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:07:37.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:07:37.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.071 seconds
[2024-05-30T08:08:07.972+0000] {processor.py:161} INFO - Started process (PID=743) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:08:07.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:08:07.976+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:08:07.976+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:08:07.981+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:08:07.980+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:08:07.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:08:08.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.066 seconds
[2024-05-30T08:08:38.249+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:08:38.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:08:38.252+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:08:38.252+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:08:38.259+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:08:38.256+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:08:38.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:08:38.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-30T08:09:08.494+0000] {processor.py:161} INFO - Started process (PID=836) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:09:08.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:09:08.497+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:09:08.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:09:08.501+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:09:08.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:09:08.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:09:08.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.052 seconds
[2024-05-30T08:09:38.626+0000] {processor.py:161} INFO - Started process (PID=847) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:09:38.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:09:38.630+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:09:38.630+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:09:38.640+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:09:38.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:09:38.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:09:38.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-30T08:10:08.825+0000] {processor.py:161} INFO - Started process (PID=858) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:10:08.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:10:08.831+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:10:08.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:10:08.839+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:10:08.837+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:10:08.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:10:08.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.071 seconds
[2024-05-30T08:10:39.121+0000] {processor.py:161} INFO - Started process (PID=870) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:10:39.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:10:39.125+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:10:39.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:10:39.130+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:10:39.129+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:10:39.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:10:39.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.056 seconds
[2024-05-30T08:11:09.417+0000] {processor.py:161} INFO - Started process (PID=881) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:11:09.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:11:09.420+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:11:09.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:11:09.426+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:11:09.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:11:09.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:11:09.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-30T08:11:39.649+0000] {processor.py:161} INFO - Started process (PID=892) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:11:39.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:11:39.653+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:11:39.652+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:11:39.663+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:11:39.660+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:11:39.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:11:39.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.079 seconds
[2024-05-30T08:12:09.917+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:12:09.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:12:09.933+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:12:09.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:12:09.936+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:12:09.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:12:09.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:12:09.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.070 seconds
[2024-05-30T08:12:40.178+0000] {processor.py:161} INFO - Started process (PID=914) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:12:40.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:12:40.183+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:12:40.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:12:40.188+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:12:40.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:12:40.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:12:40.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.061 seconds
[2024-05-30T08:13:10.423+0000] {processor.py:161} INFO - Started process (PID=925) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:13:10.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:13:10.425+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:13:10.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:13:10.429+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:13:10.427+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:13:10.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:13:10.519+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.105 seconds
[2024-05-30T08:13:40.684+0000] {processor.py:161} INFO - Started process (PID=936) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:13:40.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:13:40.687+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:13:40.686+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:13:40.691+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:13:40.689+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:13:40.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:13:40.735+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.089 seconds
[2024-05-30T08:14:10.995+0000] {processor.py:161} INFO - Started process (PID=953) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:14:10.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:14:10.998+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:14:10.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:14:11.004+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:14:11.000+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:14:11.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:14:11.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.059 seconds
[2024-05-30T08:14:41.254+0000] {processor.py:161} INFO - Started process (PID=964) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:14:41.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:14:41.262+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:14:41.260+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:14:41.283+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:14:41.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:14:41.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:14:41.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.135 seconds
[2024-05-30T08:15:11.467+0000] {processor.py:161} INFO - Started process (PID=975) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:15:11.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:15:11.470+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:15:11.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:15:11.474+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:15:11.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:15:11.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:15:11.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.043 seconds
[2024-05-30T08:15:41.701+0000] {processor.py:161} INFO - Started process (PID=986) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:15:41.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:15:41.705+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:15:41.705+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:15:41.709+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:15:41.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:15:41.710+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:15:41.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.055 seconds
[2024-05-30T08:16:12.127+0000] {processor.py:161} INFO - Started process (PID=997) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:16:12.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:16:12.131+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:16:12.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:16:12.136+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:16:12.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:16:12.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:16:12.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.072 seconds
[2024-05-30T08:16:42.372+0000] {processor.py:161} INFO - Started process (PID=1008) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:16:42.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:16:42.375+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:16:42.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:16:42.379+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:16:42.378+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:16:42.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:16:42.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-30T08:17:12.490+0000] {processor.py:161} INFO - Started process (PID=1017) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:17:12.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:17:12.492+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:17:12.491+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:17:12.498+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:17:12.494+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:17:12.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:17:12.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.051 seconds
[2024-05-30T08:17:42.609+0000] {processor.py:161} INFO - Started process (PID=1028) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:17:42.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:17:42.613+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:17:42.612+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:17:42.616+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:17:42.615+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:17:42.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:17:42.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.052 seconds
[2024-05-30T08:18:12.835+0000] {processor.py:161} INFO - Started process (PID=1039) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:18:12.835+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:18:12.837+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:18:12.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:18:12.841+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:18:12.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:18:12.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:18:12.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.050 seconds
[2024-05-30T08:18:43.072+0000] {processor.py:161} INFO - Started process (PID=1050) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:18:43.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:18:43.075+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:18:43.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:18:43.081+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:18:43.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:18:43.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:18:43.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.048 seconds
[2024-05-30T08:19:14.039+0000] {processor.py:161} INFO - Started process (PID=1061) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:19:14.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:19:14.041+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:19:14.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:19:14.048+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:19:14.046+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:19:14.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:19:14.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.065 seconds
[2024-05-30T08:19:44.289+0000] {processor.py:161} INFO - Started process (PID=1071) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:19:44.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:19:44.291+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:19:44.291+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:19:44.295+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:19:44.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:19:44.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:19:44.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.050 seconds
[2024-05-30T08:20:14.373+0000] {processor.py:161} INFO - Started process (PID=1082) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:20:14.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:20:14.375+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:20:14.374+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:20:14.379+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:20:14.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:20:14.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:20:14.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.042 seconds
[2024-05-30T08:20:44.588+0000] {processor.py:161} INFO - Started process (PID=1093) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:20:44.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:20:44.591+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:20:44.590+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:20:44.594+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:20:44.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:20:44.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:20:44.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.051 seconds
[2024-05-30T08:21:14.833+0000] {processor.py:161} INFO - Started process (PID=1104) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:21:14.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:21:14.836+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:21:14.835+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:21:14.841+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:21:14.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:21:14.842+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:21:14.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.061 seconds
[2024-05-30T08:21:45.094+0000] {processor.py:161} INFO - Started process (PID=1115) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:21:45.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:21:45.098+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:21:45.098+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:21:45.104+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:21:45.102+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:21:45.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:21:45.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.075 seconds
[2024-05-30T08:22:15.365+0000] {processor.py:161} INFO - Started process (PID=1125) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:22:15.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:22:15.367+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:22:15.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:22:15.376+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:22:15.374+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:22:15.377+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:22:15.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.061 seconds
[2024-05-30T08:22:45.610+0000] {processor.py:161} INFO - Started process (PID=1134) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:22:45.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:22:45.614+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:22:45.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:22:45.626+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:22:45.624+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:22:45.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:22:45.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.092 seconds
[2024-05-30T08:23:15.815+0000] {processor.py:161} INFO - Started process (PID=1145) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:23:15.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:23:15.821+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:23:15.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:23:15.840+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:23:15.835+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:23:15.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:23:15.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.088 seconds
[2024-05-30T08:23:46.106+0000] {processor.py:161} INFO - Started process (PID=1156) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:23:46.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:23:46.110+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:23:46.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:23:46.114+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:23:46.113+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:23:46.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:23:46.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.061 seconds
[2024-05-30T08:24:16.385+0000] {processor.py:161} INFO - Started process (PID=1168) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:24:16.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:24:16.388+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:24:16.387+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:24:16.397+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:24:16.395+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:24:16.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:24:16.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.063 seconds
[2024-05-30T08:24:46.629+0000] {processor.py:161} INFO - Started process (PID=1179) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:24:46.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:24:46.632+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:24:46.631+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:24:46.644+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:24:46.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:24:46.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:24:46.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.066 seconds
[2024-05-30T08:25:16.890+0000] {processor.py:161} INFO - Started process (PID=1189) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:25:16.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:25:16.894+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:25:16.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:25:16.900+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:25:16.897+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:25:16.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:25:16.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.080 seconds
[2024-05-30T08:25:47.102+0000] {processor.py:161} INFO - Started process (PID=1200) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:25:47.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:25:47.105+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:25:47.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:25:47.109+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:25:47.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:25:47.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:25:47.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.049 seconds
[2024-05-30T08:26:17.324+0000] {processor.py:161} INFO - Started process (PID=1211) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:26:17.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:26:17.326+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:26:17.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:26:17.331+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:26:17.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:26:17.331+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:26:17.359+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.042 seconds
[2024-05-30T08:26:47.539+0000] {processor.py:161} INFO - Started process (PID=1222) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:26:47.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:26:47.541+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:26:47.541+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:26:47.544+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:26:47.543+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:26:47.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:26:47.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.037 seconds
[2024-05-30T08:27:17.786+0000] {processor.py:161} INFO - Started process (PID=1233) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:27:17.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:27:17.788+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:27:17.788+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:27:17.792+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:27:17.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:27:17.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:27:17.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.052 seconds
[2024-05-30T08:27:48.019+0000] {processor.py:161} INFO - Started process (PID=1244) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:27:48.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:27:48.022+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:27:48.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:27:48.028+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:27:48.026+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:27:48.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:27:48.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.069 seconds
[2024-05-30T08:28:18.248+0000] {processor.py:161} INFO - Started process (PID=1255) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:28:18.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:28:18.250+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:28:18.250+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:28:18.253+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:28:18.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:28:18.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:28:18.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.040 seconds
[2024-05-30T08:28:48.453+0000] {processor.py:161} INFO - Started process (PID=1266) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:28:48.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:28:48.456+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:28:48.456+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:28:48.463+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:28:48.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:28:48.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:28:48.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.059 seconds
[2024-05-30T08:29:18.666+0000] {processor.py:161} INFO - Started process (PID=1277) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:29:18.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:29:18.667+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:29:18.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:29:18.674+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:29:18.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:29:18.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:29:18.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.043 seconds
[2024-05-30T08:29:48.846+0000] {processor.py:161} INFO - Started process (PID=1288) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:29:48.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:29:48.848+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:29:48.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:29:48.852+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:29:48.850+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:29:48.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:29:48.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.044 seconds
[2024-05-30T08:30:19.110+0000] {processor.py:161} INFO - Started process (PID=1299) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:30:19.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:30:19.112+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:30:19.112+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:30:19.116+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:30:19.115+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:30:19.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:30:19.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.042 seconds
[2024-05-30T08:30:49.238+0000] {processor.py:161} INFO - Started process (PID=1310) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:30:49.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:30:49.240+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:30:49.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:30:49.244+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:30:49.243+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:30:49.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:30:49.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.044 seconds
[2024-05-30T08:31:19.454+0000] {processor.py:161} INFO - Started process (PID=1320) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:31:19.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:31:19.458+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:31:19.457+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:31:19.465+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:31:19.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:31:19.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:31:19.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.079 seconds
[2024-05-30T08:31:49.719+0000] {processor.py:161} INFO - Started process (PID=1331) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:31:49.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:31:49.721+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:31:49.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:31:49.726+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:31:49.723+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:31:49.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:31:49.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.058 seconds
[2024-05-30T08:32:19.950+0000] {processor.py:161} INFO - Started process (PID=1342) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:32:19.951+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:32:19.954+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:32:19.954+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:32:19.966+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:32:19.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:32:19.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:32:20.008+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.077 seconds
[2024-05-30T08:32:50.164+0000] {processor.py:161} INFO - Started process (PID=1353) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:32:50.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:32:50.167+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:32:50.167+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:32:50.175+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:32:50.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:32:50.177+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:32:50.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.058 seconds
[2024-05-30T08:33:20.363+0000] {processor.py:161} INFO - Started process (PID=1364) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:33:20.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:33:20.365+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:33:20.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:33:20.368+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:33:20.367+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:33:20.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:33:20.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.047 seconds
[2024-05-30T08:33:50.564+0000] {processor.py:161} INFO - Started process (PID=1373) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:33:50.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:33:50.568+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:33:50.567+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:33:50.572+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:33:50.570+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:33:50.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:33:50.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.054 seconds
[2024-05-30T08:34:20.701+0000] {processor.py:161} INFO - Started process (PID=1384) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:34:20.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:34:20.702+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:34:20.702+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:34:20.706+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:34:20.705+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:34:20.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:34:20.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.036 seconds
[2024-05-30T08:34:50.828+0000] {processor.py:161} INFO - Started process (PID=1395) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:34:50.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:34:50.831+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:34:50.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:34:50.835+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:34:50.834+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:34:50.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:34:50.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.051 seconds
[2024-05-30T08:35:21.072+0000] {processor.py:161} INFO - Started process (PID=1406) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:35:21.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:35:21.074+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:35:21.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:35:21.077+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:35:21.076+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:35:21.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:35:21.101+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.039 seconds
[2024-05-30T08:35:51.232+0000] {processor.py:161} INFO - Started process (PID=1417) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:35:51.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:35:51.235+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:35:51.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:35:51.240+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:35:51.238+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:35:51.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:35:51.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.058 seconds
[2024-05-30T08:36:21.339+0000] {processor.py:161} INFO - Started process (PID=1428) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:36:21.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:36:21.341+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:36:21.340+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:36:21.345+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:36:21.343+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:36:21.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:36:21.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.040 seconds
[2024-05-30T08:36:51.523+0000] {processor.py:161} INFO - Started process (PID=1439) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:36:51.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:36:51.525+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:36:51.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:36:51.531+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:36:51.529+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:36:51.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:36:51.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.046 seconds
[2024-05-30T08:37:21.750+0000] {processor.py:161} INFO - Started process (PID=1450) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:37:21.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:37:21.752+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:37:21.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:37:21.757+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:37:21.756+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:37:21.758+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:37:21.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.054 seconds
[2024-05-30T08:37:51.976+0000] {processor.py:161} INFO - Started process (PID=1461) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:37:51.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:37:51.981+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:37:51.981+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:37:51.986+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:37:51.985+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:37:51.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:37:52.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.060 seconds
[2024-05-30T08:38:22.102+0000] {processor.py:161} INFO - Started process (PID=1470) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:38:22.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:38:22.104+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:38:22.104+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:38:22.108+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:38:22.107+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:38:22.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:38:22.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.050 seconds
[2024-05-30T08:38:52.374+0000] {processor.py:161} INFO - Started process (PID=1481) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:38:52.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:38:52.384+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:38:52.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:38:52.394+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:38:52.389+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:38:52.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:38:52.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.089 seconds
[2024-05-30T08:39:22.544+0000] {processor.py:161} INFO - Started process (PID=1492) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:39:22.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:39:22.546+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:39:22.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:39:22.553+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:39:22.552+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:39:22.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:39:22.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.048 seconds
[2024-05-30T08:39:52.776+0000] {processor.py:161} INFO - Started process (PID=1503) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:39:52.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:39:52.780+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:39:52.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:39:52.785+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:39:52.783+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:39:52.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:39:52.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.054 seconds
[2024-05-30T08:40:23.001+0000] {processor.py:161} INFO - Started process (PID=1514) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:40:23.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:40:23.006+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:40:23.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:40:23.013+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:40:23.010+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:40:23.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:40:23.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.062 seconds
[2024-05-30T08:40:53.217+0000] {processor.py:161} INFO - Started process (PID=1525) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:40:53.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:40:53.220+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:40:53.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:40:53.224+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:40:53.223+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:40:53.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:40:53.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.050 seconds
[2024-05-30T08:41:23.454+0000] {processor.py:161} INFO - Started process (PID=1535) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:41:23.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:41:23.455+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:41:23.455+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:41:23.460+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:41:23.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:41:23.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:41:23.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.043 seconds
[2024-05-30T08:41:53.654+0000] {processor.py:161} INFO - Started process (PID=1546) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:41:53.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:41:53.661+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:41:53.659+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:41:53.670+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:41:53.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:41:53.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:41:53.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.073 seconds
[2024-05-30T08:42:23.890+0000] {processor.py:161} INFO - Started process (PID=1556) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:42:23.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:42:23.892+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:42:23.891+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:42:23.896+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:42:23.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:42:23.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:42:23.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.047 seconds
[2024-05-30T08:42:54.134+0000] {processor.py:161} INFO - Started process (PID=1567) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:42:54.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:42:54.138+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:42:54.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:42:54.143+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:42:54.141+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:42:54.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:42:54.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.045 seconds
[2024-05-30T08:43:24.623+0000] {processor.py:161} INFO - Started process (PID=1578) to work on /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:43:24.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_test_spark.py for tasks to queue
[2024-05-30T08:43:24.627+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:43:24.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:43:24.636+0000] {logging_mixin.py:188} INFO - [2024-05-30T08:43:24.632+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_test_spark.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_test_spark.py", line 4, in <module>
    from airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2024-05-30T08:43:24.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_test_spark.py
[2024-05-30T08:43:24.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_test_spark.py took 0.066 seconds
